# Generated by Django 4.1.7 on 2023-03-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_csv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="range_from",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="range_to",
            field=models.IntegerField(null=True),
        ),
    ]
