# Generated by Django 4.1.7 on 2023-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_csv", "0002_alter_column_range_from_alter_column_range_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="range_from",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="range_to",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
