# Generated by Django 4.1.7 on 2023-03-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_csv", "0005_rename_generateddata_dataset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("name", "Full name"),
                    ("job", "Job"),
                    ("email", "Email"),
                    ("domain_name", "Domain name"),
                    ("phone_number", "Phone number"),
                    ("company", "Company name"),
                    ("text", "Text"),
                    ("randint", "Integer"),
                    ("address", "Address"),
                    ("date", "Date"),
                ],
                max_length=255,
            ),
        ),
    ]
