# Generated by Django 4.1.7 on 2023-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_csv", "0006_alter_column_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("Full name", "Full name"),
                    ("Job", "Job"),
                    ("Email", "Email"),
                    ("Domain name", "Domain name"),
                    ("Phone number", "Phone number"),
                    ("Company name", "Company name"),
                    ("Text", "Text"),
                    ("Integer", "Integer"),
                    ("Address", "Address"),
                    ("Date", "Date"),
                ],
                max_length=255,
            ),
        ),
    ]
